load("ext://restart_process", "docker_build_with_restart")

image_repo = os.getenv("TILT_IMAGE_REPO", default="registry.local:5000")
image_target = os.getenv("TILT_GATEWAY_IMAGE_TARGET", default="tilt")

compile_cmd = "CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/gateway cmd/gateway/main.go"

local_resource(
  "generate-gqlgen",
  "bin/prepare.sh -bg",
  trigger_mode=TRIGGER_MODE_MANUAL,
  labels=["gateway"],
  auto_init=False,
)

local_resource(
  name="gateway-compile",
  cmd=compile_cmd,
  trigger_mode=TRIGGER_MODE_AUTO,
  deps=["pkg", "cmd/backend/main.go"],
  labels=["gateway"],
  ignore=[
    "pkg/graphql", 
    "pkg/resolvers/generated",
    "pkg/*/loader"
  ]
)

docker_build_with_restart(
  "{image_repo}/gateway".format(image_repo=image_repo),
  context=".",
  dockerfile="Dockerfile",
  target=image_target,
  entrypoint=["/usr/local/bin/gateway"],
  only=["bin/gateway"],
  live_update=[
    sync("bin/gateway", "/usr/local/bin/gateway"),
  ]
)

k8s_resource(
  workload="perspex-gateway",
  resource_deps=["postgresql", "perspex-backend"],
  labels=["gateway"],
)
