load('ext://restart_process', 'custom_build_with_restart', 'docker_build_with_restart')
load('ext://local_output', 'local_output')

image_repo = os.getenv('TILT_IMAGE_REPO','registry.local:5000')
update_settings(suppress_unused_image_warnings=["registry.local:5000/migration"])

custom_build(
  "{image_repo}/migration".format(image_repo=image_repo),
  command="docker build --tag ${EXPECTED_REF} .",
  deps=['./services/migration/src/perspex'],
)

local_resource(
  "version",
  auto_init=False,
  trigger_mode=TRIGGER_MODE_MANUAL,
  cmd="bin/migration.sh -p src/perspex -l -m version",
  labels=["migrations"]
)

local_resource(
  "create",
  auto_init=False,
  trigger_mode=TRIGGER_MODE_MANUAL,
  cmd="bin/migration.sh -p src/perspex -c",
  labels=["migrations"]
)

local_resource(
  "upgrade-head",
  auto_init=False,
  trigger_mode=TRIGGER_MODE_MANUAL,
  cmd="bin/migration.sh -l -p src/perspex -m up ",
  labels=["migrations"]
)

local_resource(
  "downgrade-last",
  auto_init=False,
  trigger_mode=TRIGGER_MODE_MANUAL,
  cmd="bin/migration.sh -p src/perspex -l -n 1 -m down",
  labels=["migrations"]
)

local_resource(
  "drop-all",
  auto_init=False,
  trigger_mode=TRIGGER_MODE_MANUAL,
  cmd="bin/migration.sh -p src/perspex -l -d",
  labels=["migrations"]
)
