// @generated by protoc-gen-connect-web v0.5.0 with parameter "target=ts"
// @generated from file users/v1/user.proto (package users.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteUserRequest, DeleteUserResponse, ModifyUserRequest, ModifyUserResponse, RegisterUserRequest, RegisterUserResponse, RetrieveUserRequest, RetrieveUserResponse, RetrieveUsersPageRequest, RetrieveUsersPageResponse, RetrieveUsersRequest, RetrieveUsersResponse } from "./user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service users.v1.UserService
 */
export const UserService = {
  typeName: "users.v1.UserService",
  methods: {
    /**
     * @generated from rpc users.v1.UserService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserRequest,
      O: DeleteUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.v1.UserService.ModifyUser
     */
    modifyUser: {
      name: "ModifyUser",
      I: ModifyUserRequest,
      O: ModifyUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.v1.UserService.RegisterUser
     */
    registerUser: {
      name: "RegisterUser",
      I: RegisterUserRequest,
      O: RegisterUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.v1.UserService.RetrieveUser
     */
    retrieveUser: {
      name: "RetrieveUser",
      I: RetrieveUserRequest,
      O: RetrieveUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.v1.UserService.RetrieveUsers
     */
    retrieveUsers: {
      name: "RetrieveUsers",
      I: RetrieveUsersRequest,
      O: RetrieveUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.v1.UserService.RetrieveUsersPage
     */
    retrieveUsersPage: {
      name: "RetrieveUsersPage",
      I: RetrieveUsersPageRequest,
      O: RetrieveUsersPageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

